name: Mod Request
description: Request a new mod to be added to the modpack
title: "[MOD REQUEST] "
labels: ["mod-request", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Request a mod to be added to the modpack!

  - type: input
    id: mod_name
    attributes:
      label: Mod Name
      description: What is the name of the mod?
      placeholder: "For example: StoreTweaks"
    validations:
      required: true

  - type: input
    id: mod_link
    attributes:
      label: Thunderstore Link
      description: Provide the Thunderstore link to the mod
      placeholder: "https://thunderstore.io/c/lethal-company/p/Author/ModName/"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Mod Category
      description: What type of mod is this?
      options:
        - Equipment/Items/Scrap
        - Moons/Interiors
        - Enemies
        - Cosmetics/Suits
        - QoL/Tweaks
        - Performance
        - Audio/Visual
        - Other
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should this mod be added?
      description: Explain why would you like to see this mod in the modpack
      placeholder: |
        This mod would improve...
    validations:
      required: true

  - type: input
    id: notes
    attributes:
      label: "Additional Notes"
      description: "Any other information that might help us review this mod?"
    validations:
      required: false

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Check
      description: Have you verified these?
      options:
        - label: The mod is compatible with v73 of Lethal Company
          required: true
        - label: The mod doesn't conflict with existing mods in the pack
          required: false
        - label: The mod fits the modpack theme
          required: false
